import type { Metadata } from "next";
import { NavbarWrapper } from "@/components/layout/navbar-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { getLanguage } from "@/lib/translations/language";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = await getLanguage();
  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen flex flex-col">
            <NavbarWrapper />
            <main className="flex-1">{children}</main>
            <Toaster
              position="top-center"
              closeButton={false}
              toastOptions={{
                duration: 1500,
                className: "text-red-600 font-medium text-sm",
              }}
            />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
